ALTER TABLE PROD.CUSTOMER.CUSTOMERS DROP COLUMN REGION;
ALTER WAREHOUSE ANALYTICS_WH SET WAREHOUSE_SIZE = '2XLARGE';
CREATE VIEW PROD.REPORTING.CUSTOMER_EXPORT AS
SELECT * FROM PROD.CUSTOMER.CUSTOMERS;
